source 'https://github.com/Artsy/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'

pod 'SDWebImage', '~> 3.7.1'
pod 'MBProgressHUD', '~> 0.9'
pod 'ReactiveCocoa'
pod 'FMDB'
pod 'MKNetworkKit', '~> 0.87'
pod 'SSKeychain', '~> 1.2.2'
pod 'IQKeyboardManager', '~> 3.2.0.3'
pod 'AFNetworking'
pod 'YTKNetwork'
pod 'YTKKeyValueStore'
pod 'pop'
pod 'Qiniu'
pod 'MJExtension','~> 3.0.0'
pod 'MJRefresh','~> 3.0.7'
pod 'Masonry'
pod 'AMap2DMap'
pod 'AMapSearch'
pod 'YYWebImage'
pod 'YYText'
pod 'UIActivityIndicator-for-SDWebImage'
